export const ABI_CONFIG = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_from',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'NAME',
        type: 'string',
      },
    ],
    name: 'CERTIFICATE_GENERATED',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'from',
        type: 'address',
      },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_from',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'NAME',
        type: 'string',
      },
    ],
    name: 'UNIVERSITY_ADDED',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'string', name: 'UNI_NAME', type: 'string' }],
    name: 'ADD_NEW_UNIVERSITY',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_student_name', type: 'string' },
      { internalType: 'string', name: '_program', type: 'string' },
      { internalType: 'string', name: '_issue_date', type: 'string' },
      { internalType: 'string', name: '_department', type: 'string' },
      { internalType: 'string', name: '_contact_number', type: 'string' },
      { internalType: 'string', name: '_cgpa', type: 'string' },
      { internalType: 'string', name: '_tenure', type: 'string' },
      { internalType: 'string', name: '_certificate_uri', type: 'string' },
      { internalType: 'address', name: '_student_address', type: 'address' },
      { internalType: 'uint256', name: '_uni_id', type: 'uint256' },
    ],
    name: 'GENERATE_CERTIFICATE',
    outputs: [{ internalType: 'string', name: 'message', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'GET_ALL_UNIVERSITIES',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'university_wallet_address',
            type: 'address',
          },
          { internalType: 'string', name: 'uni_name', type: 'string' },
          {
            internalType: 'address[]',
            name: 'whitelisted_accounts',
            type: 'address[]',
          },
        ],
        internalType: 'struct SBT_TOKEN.UNIVERSITY[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'GET_MY_CERTIFICATES',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'student_name', type: 'string' },
          { internalType: 'string', name: 'program', type: 'string' },
          { internalType: 'string', name: 'issue_date', type: 'string' },
          { internalType: 'string', name: 'department', type: 'string' },
          { internalType: 'string', name: 'contact_number', type: 'string' },
          { internalType: 'string', name: 'cgpa', type: 'string' },
          { internalType: 'string', name: 'tenure', type: 'string' },
          { internalType: 'string', name: 'remarks', type: 'string' },
          { internalType: 'string', name: 'certificate_uri', type: 'string' },
          { internalType: 'uint256', name: 'university_id', type: 'uint256' },
        ],
        internalType: 'struct SBT_TOKEN.CERTIFICATE[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'user_wallet_address',
        type: 'address',
      },
    ],
    name: 'GET_USER_CERTIFICATES',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'student_name', type: 'string' },
          { internalType: 'string', name: 'program', type: 'string' },
          { internalType: 'string', name: 'issue_date', type: 'string' },
          { internalType: 'string', name: 'department', type: 'string' },
          { internalType: 'string', name: 'contact_number', type: 'string' },
          { internalType: 'string', name: 'cgpa', type: 'string' },
          { internalType: 'string', name: 'tenure', type: 'string' },
          { internalType: 'string', name: 'remarks', type: 'string' },
          { internalType: 'string', name: 'certificate_uri', type: 'string' },
          { internalType: 'uint256', name: 'university_id', type: 'uint256' },
        ],
        internalType: 'struct SBT_TOKEN.CERTIFICATE[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'GET_WHITELISTED_ACCOUNTS',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address', name: 'whitelist_account', type: 'address' },
    ],
    name: 'WHITELIST_ADDRESS_FOR_UNIVERSITY',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'string', name: 'uri', type: 'string' },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'give',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'string', name: 'uri', type: 'string' },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'take',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'unequip',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'universities',
    outputs: [
      {
        internalType: 'address',
        name: 'university_wallet_address',
        type: 'address',
      },
      { internalType: 'string', name: 'uni_name', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userCertifacte',
    outputs: [
      { internalType: 'string', name: 'student_name', type: 'string' },
      { internalType: 'string', name: 'program', type: 'string' },
      { internalType: 'string', name: 'issue_date', type: 'string' },
      { internalType: 'string', name: 'department', type: 'string' },
      { internalType: 'string', name: 'contact_number', type: 'string' },
      { internalType: 'string', name: 'cgpa', type: 'string' },
      { internalType: 'string', name: 'tenure', type: 'string' },
      { internalType: 'string', name: 'remarks', type: 'string' },
      { internalType: 'string', name: 'certificate_uri', type: 'string' },
      { internalType: 'uint256', name: 'university_id', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
